networks:
  backend:

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/var/lib/postgresql/data:/var/lib/postgresql/data:rw
    networks:
      - backend
    environment:
      POSTGRES_DB: relapse
      POSTGRES_USER: relapse_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=C

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - backend

  relapse:
    image: gchr.io/clokep/relapse:latest
    container_name: relapse
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/data:/data:rw
    ports:
      - 8008:8008
    networks:
      - backend
    environment:
      RELAPSE_CONFIG_DIR: /data
      RELAPSE_CONFIG_PATH: /data/homeserver.yaml
    depends_on:
      - postgres

  relapse-generic-worker-1:
    image: gchr.io/clokep/relapse:latest
    container_name: relapse-generic-worker-1
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/relapse-generic-worker-1.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - backend
    volumes:
      - ${VOLUME_PATH}/data:/data:rw # Replace VOLUME_PATH with the path to your Relapse volume
    environment:
      RELAPSE_WORKER: relapse.app.generic_worker
    # Expose port if required so your reverse proxy can send requests to this worker
    # Port configuration will depend on how the http listener is defined in the worker configuration file
    ports:
      - 8081:8081
    depends_on:
      - relapse

  relapse-federation-sender-1:
    image: gchr.io/clokep/relapse:latest
    container_name: relapse-federation-sender-1
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/relapse-federation-sender-1.yaml"]
    healthcheck:
      disable: true
    networks:
      - backend
    volumes:
      - ${VOLUME_PATH}/data:/data:rw # Replace VOLUME_PATH with the path to your Relapse volume
    environment:
      RELAPSE_WORKER: relapse.app.federation_sender
    depends_on:
      - relapse
